name: Release Alpha GUI Build

on:
  workflow_dispatch:

jobs:
  release-alpha-gui:
    name: Release Alpha GUI Build
    runs-on: ubuntu-latest
    steps:
      - name: Find latest successful build_alpha_gui run
        id: find_run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TACHYON_CLIENT }}
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: 'tachyon-gg',
              repo: 'tachyon-client',
              workflow_id: 'build_alpha_gui.yml',
              branch: 'alpha',
              status: 'completed',
              per_page: 10
            });
            const successful = runs.data.workflow_runs.find(run => run.conclusion === 'success');
            if (!successful) throw new Error('No successful build_alpha_gui run found');
            core.setOutput('run_id', successful.id);

      - name: Download GUI artifact
        uses: actions/download-artifact@v4
        with:
          name: tachyon-gui-ubuntu-latest-alpha
          path: ./artifact-ubuntu
          run-id: ${{ steps.find_run.outputs.run_id }}
          github-token: ${{ secrets.TACHYON_CLIENT }}
          
      - name: Download GUI artifact (macOS)
        uses: actions/download-artifact@v4
        with:
          name: tachyon-gui-macos-latest-alpha
          path: ./artifact-macos
          run-id: ${{ steps.find_run.outputs.run_id }}
          github-token: ${{ secrets.TACHYON_CLIENT }}

      - name: Download GUI artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: tachyon-gui-windows-latest-alpha
          path: ./artifact-windows
          run-id: ${{ steps.find_run.outputs.run_id }}
          github-token: ${{ secrets.TACHYON_CLIENT }}

      - name: Set version from artifact (fallback to timestamp)
        id: version
        run: |
          # Try to extract version from a file, or fallback to timestamp
          VERSION_FILE=$(find ./artifact-ubuntu ./artifact-macos ./artifact-windows -type f -name "*.json" | head -n 1)
          if [ -n "$VERSION_FILE" ]; then
            VERSION=$(jq -r '.version' "$VERSION_FILE")
          else
            VERSION="manual-$(date +%Y%m%d%H%M%S)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Release to public repo
        uses: softprops/action-gh-release@v2
        with:
          tag_name: alpha-${{ steps.version.outputs.version }}
          name: Alpha Build ${{ steps.version.outputs.version }}
          files: |
            artifact-ubuntu/**
            artifact-macos/**
            artifact-windows/**
          draft: false
          prerelease: true