name: Release Alpha CLI Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for this release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  release-alpha-cli:
    name: Release Alpha CLI Build
    runs-on: ubuntu-latest
    steps:
      - name: Find run for tag
        id: find_run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TACHYON_GG }}
          script: |
            const version = "${{ github.event.inputs.version }}";
            if (!version) throw new Error('No version input provided');
            const tag = `cli-alpha-${version}`;
            // Find workflow runs triggered by the tag (version)
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: 'tachyon-gg',
              repo: 'tachyon-client',
              workflow_id: 'build_cli.yml',
              status: 'completed',
              per_page: 100
            });
            let foundRun = null;
            for (const run of runs.data.workflow_runs) {
              if (run.event === 'push' && run.head_branch === tag) {
                foundRun = run;
                break;
              }
              if (run.event === 'create' && run.head_branch === tag) {
                foundRun = run;
                break;
              }
              if (run.event === 'push' && run.ref === `refs/tags/${tag}`) {
                foundRun = run;
                break;
              }
            }
            if (!foundRun) throw new Error(`No workflow run found for tag ${tag}`);
            core.setOutput('run_id', String(foundRun.id));

      - name: Download CLI artifact (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: tachyon-cli-ubuntu-latest-alpha-${{ github.event.inputs.version }}
          path: ./artifact-ubuntu
          repository: tachyon-gg/tachyon-client
          run-id: ${{ steps.find_run.outputs.run_id }}
          github-token: ${{ secrets.TACHYON_GG }}

      - name: Download CLI artifact (macOS)
        uses: actions/download-artifact@v4
        with:
          name: tachyon-cli-macos-latest-alpha-${{ github.event.inputs.version }}
          path: ./artifact-macos
          repository: tachyon-gg/tachyon-client
          run-id: ${{ steps.find_run.outputs.run_id }}
          github-token: ${{ secrets.TACHYON_GG }}

      - name: Download CLI artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: tachyon-cli-windows-latest-alpha-${{ github.event.inputs.version }}
          path: ./artifact-windows
          repository: tachyon-gg/tachyon-client
          run-id: ${{ steps.find_run.outputs.run_id }}
          github-token: ${{ secrets.TACHYON_GG }}

      - name: Copy Ubuntu artifacts (.deb and .rpm)
        run: |
          mkdir -p release-artifacts
          find artifact-ubuntu -type f \( -name "*.deb" -o -name "*.rpm" \) -exec cp {} release-artifacts/ \;

      - name: Copy macOS artifacts (.dmg)
        run: |
          find artifact-macos -type f -name "*.dmg" -exec cp {} release-artifacts/ \;

      - name: Copy Windows artifacts (.msi)
        run: |
          find artifact-windows -type f -name "*.msi" -exec cp {} release-artifacts/ \;

      - name: Release to public repo
        uses: softprops/action-gh-release@v2
        with:
          tag_name: alpha-${{ github.event.inputs.version }}
          name: Alpha Build ${{ github.event.inputs.version }}
          token: ${{ secrets.TACHYON_GG }}
          files: release-artifacts/*
          draft: false
          prerelease: true
